services:
  db:
    image: postgres
    environment:
      POSTGRES_USER: gift
      POSTGRES_PASSWORD: giftpwd
    ports:
      - '5432:5432'
  pgadmin:
    image: dpage/pgadmin4
    ports:
      - '8888:80'
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@admin.com
      PGADMIN_DEFAULT_PASSWORD: pggift
